version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "my_todo_db"
    env_file:
      - ./.env
    ports:
      - "54320:5432"
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
